// CII FastTrack — Subject Data
// Source: CII 2026 Qualifications Brochure + CII Results Information page

const SUBJECTS = [
  // === Core Mandatory ===
  {
    code: 'M05',
    nameEN: 'Insurance Law',
    nameZH: '保險法',
    category: 'core-mandatory',
    categoryLabel: '📕 Core 必修',
    credits: 25,
    level: 4,
    assessmentMode: 'mixed',
    assessmentLabel: '🔄 Mixed 混合',
    mcqPassMark: 65,
    cwPassMark: 60,
    mcqQuestions: '50 MCQ (40 standard + 10 multiple response)',
    mcqTime: '60 mins',
    cwCount: 1,
    cwWordRange: 'N/A (specimen provided)',
    studyHours: 120,
    recommendedWeeks: 8,
    notes: '必修。Mixed: Coursework 須前6個月提交 + MCQ 18個月內完成',
    prerequisite: [],
    syllabusUrl: 'https://www.cii.co.uk/learning/qualifications/unit-insurance-law-m05/',
    withdrawing: false
  },
  // === Core Option: M92 or 530 ===
  {
    code: 'M92',
    nameEN: 'Insurance Business and Finance',
    nameZH: '保險商業與財務',
    category: 'core-option',
    categoryLabel: '📗 Core Option 核心選項',
    credits: 25,
    level: 4,
    assessmentMode: 'mixed',
    assessmentLabel: '🔄 Mixed 混合',
    mcqPassMark: 65,
    cwPassMark: 60,
    mcqQuestions: '25 MCQ + 5 case studies (5 MCQ each)',
    mcqTime: '90 mins',
    cwCount: 1,
    cwWordRange: 'N/A (specimen provided)',
    studyHours: 100,
    recommendedWeeks: 7,
    notes: '與530二選一。Mixed: Coursework 前6個月 + MCQ 18個月',
    prerequisite: [],
    syllabusUrl: 'https://www.cii.co.uk/learning/qualifications/diploma-in-insurance-qualification/unit-insurance-business-and-finance-m92/',
    withdrawing: false
  },
  {
    code: '530',
    nameEN: 'Economics and Business',
    nameZH: '經濟學與商業',
    category: 'core-option',
    categoryLabel: '📗 Core Option 核心選項',
    credits: 30,
    level: 6,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 150,
    recommendedWeeks: 10,
    notes: '與M92二選一。3份作業，12個月有效期',
    prerequisite: [],
    syllabusUrl: 'https://www.cii.co.uk/learning/qualifications/diploma-in-insurance-qualification/unit-insurance-business-and-finance-m92/',
    withdrawing: false
  },
  // === Core Option: 820 / 930 / 960 ===
  {
    code: '820',
    nameEN: 'Advanced Claims',
    nameZH: '高級理賠',
    category: 'core-option',
    categoryLabel: '📗 Core Option 核心選項',
    credits: 30,
    level: 6,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 150,
    recommendedWeeks: 10,
    notes: '與930/960三選一。Coursework 通過率 ~97%',
    prerequisite: ['M85'],
    syllabusUrl: 'https://www.cii.co.uk/learning/qualifications/unit-advanced-claims-820/',
    withdrawing: false
  },
  {
    code: '930',
    nameEN: 'Advanced Insurance Broking',
    nameZH: '高級保險經紀',
    category: 'core-option',
    categoryLabel: '📗 Core Option 核心選項',
    credits: 30,
    level: 6,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 150,
    recommendedWeeks: 10,
    notes: '與820/960三選一。適合 Broking 方向',
    prerequisite: ['M81'],
    syllabusUrl: 'https://www.cii.co.uk/learning/qualifications/unit-930/',
    withdrawing: false
  },
  {
    code: '960',
    nameEN: 'Advanced Underwriting',
    nameZH: '高級核保',
    category: 'core-option',
    categoryLabel: '📗 Core Option 核心選項',
    credits: 30,
    level: 6,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 150,
    recommendedWeeks: 10,
    notes: '與820/930三選一。適合 Underwriting 方向',
    prerequisite: ['M80'],
    syllabusUrl: 'https://www.cii.co.uk/learning/qualifications/advanced-diploma-in-insurance-qualification/unit-advanced-underwriting-960/',
    withdrawing: false
  },
  // === Electives ===
  {
    code: '945',
    nameEN: 'Marketing Insurance Products and Services',
    nameZH: '保險產品與服務營銷',
    category: 'elective',
    categoryLabel: '📘 Elective 選修',
    credits: 30,
    level: 6,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 150,
    recommendedWeeks: 10,
    notes: '',
    prerequisite: [],
    syllabusUrl: '',
    withdrawing: false
  },
  {
    code: '990',
    nameEN: 'Insurance Corporate Management',
    nameZH: '保險企業管理',
    category: 'elective',
    categoryLabel: '📘 Elective 選修',
    credits: 30,
    level: 6,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 150,
    recommendedWeeks: 10,
    notes: '',
    prerequisite: [],
    syllabusUrl: '',
    withdrawing: false
  },
  {
    code: '991',
    nameEN: 'London Market Insurance Specialisation',
    nameZH: '倫敦市場保險專業',
    category: 'elective',
    categoryLabel: '📘 Elective 選修 ⚠️',
    credits: 50,
    level: 7,
    assessmentMode: 'dissertation',
    assessmentLabel: '📄 Dissertation 論文',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 1,
    cwWordRange: '10,000-11,000 words',
    studyHours: 180,
    recommendedWeeks: 12,
    notes: '⚠️ 2025/12/31 停止新報名。最後提交 2027/7/6。不列入推薦路徑。',
    prerequisite: [],
    syllabusUrl: '',
    withdrawing: true
  },
  {
    code: '992',
    nameEN: 'Risk Management in Insurance',
    nameZH: '保險風險管理',
    category: 'elective',
    categoryLabel: '📘 Elective 選修',
    credits: 30,
    level: 6,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 150,
    recommendedWeeks: 10,
    notes: '',
    prerequisite: [],
    syllabusUrl: '',
    withdrawing: false
  },
  {
    code: '993',
    nameEN: 'Advances in Strategic Risk Management in Insurance',
    nameZH: '保險策略風險管理進階',
    category: 'elective',
    categoryLabel: '📘 Elective 選修',
    credits: 50,
    level: 7,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 180,
    recommendedWeeks: 12,
    notes: '高學分效率：50 學分/科',
    prerequisite: [],
    syllabusUrl: '',
    withdrawing: false
  },
  {
    code: '994',
    nameEN: 'Insurance Market Specialisation',
    nameZH: '保險市場專業',
    category: 'elective',
    categoryLabel: '📘 Elective 選修 ⚠️',
    credits: 50,
    level: 7,
    assessmentMode: 'dissertation',
    assessmentLabel: '📄 Dissertation 論文',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 1,
    cwWordRange: '10,000-11,000 words',
    studyHours: 180,
    recommendedWeeks: 12,
    notes: '⚠️ 2025/12/31 停止新報名。最後提交 2027/7/6。不列入推薦路徑。',
    prerequisite: [],
    syllabusUrl: '',
    withdrawing: true
  },
  {
    code: '995',
    nameEN: 'Strategic Underwriting',
    nameZH: '策略核保',
    category: 'elective',
    categoryLabel: '📘 Elective 選修',
    credits: 30,
    level: 6,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 150,
    recommendedWeeks: 10,
    notes: '',
    prerequisite: [],
    syllabusUrl: '',
    withdrawing: false
  },
  {
    code: '996',
    nameEN: 'Strategic Claims Management',
    nameZH: '策略理賠管理',
    category: 'elective',
    categoryLabel: '📘 Elective 選修',
    credits: 30,
    level: 6,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 150,
    recommendedWeeks: 10,
    notes: '',
    prerequisite: [],
    syllabusUrl: '',
    withdrawing: false
  },
  {
    code: '997',
    nameEN: 'Advanced Risk Financing and Transfer',
    nameZH: '高級風險融資與轉移',
    category: 'elective',
    categoryLabel: '📘 Elective 選修',
    credits: 30,
    level: 6,
    assessmentMode: 'coursework',
    assessmentLabel: '📝 Coursework 作業',
    mcqPassMark: null,
    cwPassMark: 50,
    mcqQuestions: '—',
    mcqTime: '—',
    cwCount: 3,
    cwWordRange: '3,200-4,200 words each',
    studyHours: 150,
    recommendedWeeks: 10,
    notes: '',
    prerequisite: [],
    syllabusUrl: '',
    withdrawing: false
  }
];

// Core rules for Advanced Diploma
const CORE_RULES = {
  m05: { required: true, codes: ['M05'], label: 'M05 Insurance Law（必修）' },
  m92or530: { required: true, codes: ['M92', '530'], choose: 1, label: 'M92 或 530（二選一）' },
  '820or930or960': { required: true, codes: ['820', '930', '960'], choose: 1, label: '820 / 930 / 960（三選一）' }
};

const TARGET_CREDITS = 290;
